In [113]:
import numpy as np
import pandas as pd
from copy import copy, deepcopy
import math

In [80]:
dataframe = pd.read_csv('./q1-dataset/user-shows.txt', sep='\s+',header=None)


In [81]:
R = np.array(dataframe)
P = np.zeros((R.shape[0],R.shape[0]))
Q = np.zeros((R.shape[1],R.shape[1]))
for i in range(R.shape[0]):
    P[i][i] = np.sum(R[i,:])
for i in range(R.shape[1]):
    Q[i][i] = np.sum(R[:,i])

In [82]:
# R = np.array([[1,0,1],[1,0,0],[1,1,1],[1,0,1]])
# P = np.zeros((R.shape[0],R.shape[0]))
# Q = np.zeros((R.shape[1],R.shape[1]))
# for i in range(R.shape[0]):
#     P[i][i] = np.sum(R[i,:])
# for i in range(R.shape[1]):
#     Q[i][i] = np.sum(R[:,i])

In [83]:
def pw(A, b):
    Ac = copy(A)
    for i in range(Ac.shape[0]):
        for j in range(Ac.shape[1]):
            if Ac[i,j]!=0:
                Ac[i,j] = Ac[i,j]**b
    return Ac

In [84]:
#item to item similarity matrix
Si = pw(Q,-1/2).dot(R.T.dot(R.dot(pw(Q,-1/2))))
Si

array([[1.        , 0.32094021, 0.24316061, ..., 0.05605477, 0.08836543,
        0.01237116],
       [0.32094021, 1.        , 0.47375905, ..., 0.10409765, 0.12494694,
        0.02821382],
       [0.24316061, 0.47375905, 1.        , ..., 0.11327989, 0.11157299,
        0.00723158],
       ...,
       [0.05605477, 0.10409765, 0.11327989, ..., 1.        , 0.04931793,
        0.        ],
       [0.08836543, 0.12494694, 0.11157299, ..., 0.04931793, 1.        ,
        0.        ],
       [0.01237116, 0.02821382, 0.00723158, ..., 0.        , 0.        ,
        1.        ]])

In [85]:
Su = pw(P,-1/2).dot(R.dot(R.T.dot(pw(P,-1/2))))
Su

array([[1.        , 0.03314968, 0.07644708, ..., 0.07559289, 0.09258201,
        0.03877834],
       [0.03314968, 1.        , 0.02956562, ..., 0.0877058 , 0.07161149,
        0.        ],
       [0.07644708, 0.02956562, 1.        , ..., 0.20225996, 0.05504819,
        0.13834289],
       ...,
       [0.07559289, 0.0877058 , 0.20225996, ..., 1.        , 0.        ,
        0.10259784],
       [0.09258201, 0.07161149, 0.05504819, ..., 0.        , 1.        ,
        0.        ],
       [0.03877834, 0.        , 0.13834289, ..., 0.10259784, 0.        ,
        1.        ]])

In [86]:
CFi = R.dot(Si)
CFi

array([[ 9.60753925, 13.10317571, 12.23318216, ...,  3.21104654,
         3.1958345 ,  0.5460337 ],
       [ 4.36209878,  7.69620486,  7.48711214, ...,  2.5659889 ,
         2.16145674,  0.35271962],
       [ 8.38784944, 16.61201283, 14.99775822, ...,  4.48553862,
         4.63638336,  0.57006572],
       ...,
       [ 1.35142806,  3.06385022,  2.19960949, ...,  0.505658  ,
         0.56492792,  0.10841235],
       [ 4.30668052,  7.52755966,  7.98718359, ...,  2.76060253,
         2.31754441,  0.32536496],
       [ 4.09378095,  7.67177907,  7.51854526, ...,  2.04293639,
         2.28842818,  0.26419831]])

In [87]:
CFu = Su.dot(R)
CFu

array([[2.38694740e+02, 6.23151008e+02, 5.71703488e+02, ...,
        4.83274279e+01, 4.21198998e+01, 1.13858692e+00],
       [1.33694107e+02, 4.19077188e+02, 4.02414436e+02, ...,
        4.54437612e+01, 3.30921828e+01, 8.77272416e-01],
       [2.11111685e+02, 7.62741976e+02, 6.67605242e+02, ...,
        6.40146288e+01, 6.02625946e+01, 1.19935843e+00],
       ...,
       [1.15245426e+02, 4.80104040e+02, 3.20864824e+02, ...,
        2.40099342e+01, 2.40418785e+01, 7.23715847e-01],
       [1.08032264e+02, 3.39089352e+02, 3.65569102e+02, ...,
        4.03555262e+01, 2.95288560e+01, 6.09419012e-01],
       [1.66264271e+02, 5.63207472e+02, 5.31698345e+02, ...,
        4.65848688e+01, 4.67656966e+01, 7.94526464e-01]])

In [133]:
shows = np.array(pd.read_csv('./q1-dataset/shows.txt', sep='\s+',header=None))
shows = shows.reshape((shows.shape[0],))
f = open('shows.txt', 'w+')


In [134]:
f.write('item-item shows:\n')
CFiAlex = copy(CFi[499, 0:100])
for i in range(5):
    idx = CFiAlex.argmax()
    f.write('{} {}\n'.format(shows[idx], CFiAlex[idx]))
    CFiAlex[idx] = -math.inf

In [136]:
f.write('user-user shows:\n')
CFuAlex = copy(CFu[499, 0:100])
for i in range(5):
    idx = CFuAlex.argmax()
    f.write('{} {}\n'.format(shows[idx], CFuAlex[idx]))
    CFuAlex[idx] = -math.inf

In [137]:
f.close()